/*
 * date_proc.c - remote procedures; called by server stub.
 */
#include <rpc/rpc.h>
/* standard RPC include file */
#include <time.h>
#include <sys/types.h>
#include "date.h"
#include <sys/sysinfo.h>
#include <malloc.h>
/* this file is generated by rpcgen */
#define MAX_LEN 200
/*
 * Return the binary date and time.
 */
char ** date_1(long *option)
{
    struct tm *timeptr; /* Pointer to time structure      */
    time_t clock;       /* Clock value (in secs)          */
    static char *ptr;   /* Return string                  */
    static char err[] = "Invalid Response \0";
    static char s[MAX_LEN];
    clock = time(0);
    timeptr = localtime(&clock);
    switch(*option)
        {
        case 1: strftime(s,MAX_LEN,"%A, %B %d, %Y",timeptr);
                ptr=s;
                break;
        case 2: strftime(s,MAX_LEN,"%T",timeptr);
                ptr=s;
                break;
        case 3: strftime(s,MAX_LEN,"%A, %B %d, %Y - %T",timeptr);
                ptr=s;
                break;
        default: ptr=err;
                 break;
        }
    return(&ptr);
}

char ** cpu_usage_1(long *option){
    struct sysinfo info;
    static char *ptr2;
    static char s2[MAX_LEN];
    char buffer[MAX_LEN];
    sysinfo(&info);
    sprintf(buffer, "Total Ram: %ld\n  Available Ram: %ld\n  Shared Ram: %ld\n  Buffer Ram:%ld\n  Total Swap Space: %ld\n  Free Swap Space: %ld\n  Processes: %hd", info.totalram, info.freeram, info.sharedram, info.bufferram, info.totalswap, info.freeswap, info.procs);
    strcpy(s2, buffer);
    ptr2=s2;
    return (&ptr2);
}

char ** memory_usage_1(long *option){
    struct mallinfo info;
    static char *ptr3;
    static char s3[MAX_LEN];
    char buffer[MAX_LEN];
    info=mallinfo();
    sprintf(buffer, "Total allocated space(bytes): %d\n  Total free space(bytes): %d", info.uordblks, info.fordblks);
    strcpy(s3, buffer);
    ptr3=s3;
    return (&ptr3);
}

char ** load_proc_per_minute_1(long *option){
    struct sysinfo info;
    static char *ptr4;
    static char s4[MAX_LEN];
    char buffer[MAX_LEN];
    sysinfo(&info);
    sprintf(buffer, "1 Minute load average: %ld\n  5 Minute load average: %ld\n  15 Minute load average: %ld", info.loads[0], info.loads[1], info.loads[2]);
    strcpy(s4, buffer);
    ptr4=s4;
    return (&ptr4);
}
